config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'vin', to:'pages#vin', as: :vin
  get 'home',to:'pages#home', as: :home
  get 'terroir',to:'pages#terroir', as: :terroir
  get 'engagement',to:'pages#engagement', as: :engagement
  get 'histoire',to:'pages#histoire', as: :histoire
  get 'cgv',to:'pages#cgv', as: :cgv
  get 'donneepersonnelles',to:'pages#donneepersonnelles', as: :donneepersonnelles
  get 'mentionslegales',to:'pages#mentionslegales', as: :mentionslegales
  get 'nous', to: 'pages#nous', as: :nous
  get 'contact', to: 'contacts#new', as: :contact
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new contact_params
    if @contact.valid?
        MessageMailer.contact(@contact).deliver_now
        redirect_to new_contact_url
        flash[:notice] = "We have received your contact and will be in touch soon!"
    else
        flash[:notice] = "There was an error sending your contact. Please try again."
        render :new
    end
  end

  private

  def contact_params
      params.require(:contact).permit(:name, :email, :phone_number, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :vin, :engagement, :terroir, :histoire, :art, :cgv, :donneepersonnelles, :mentionslegales, :nous]

  def home
  end

  def vin
  end

  def engagement
  end

  def terroir
  end

  def histoire
  end

  def cgv
  end

  def donneespersonnelles
  end

  def mentionslegales
  end

  def nous
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="background-image flex-centered" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dbqpc6nk9/image/upload/v1574263665/h9gr6wyoq9fop23fu8w6.jpg);    background-size: cover;">
  <div class="inner-content pl-2 pr-2" style="    margin: auto;">
<div style="background-image: url(../../../app/assets/images/Logo-JPH-sans-fond.png)"> </div>

    <h3 class = "contact" style ="color: white;">Nous sommes joignables par mail à l'adresse : levinquifaitsens@gmail.com</h3>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="google-site-verification" content="NztEnHobcpZPEUYD9OhK_5tfX_-r5F8nOxIbTq2Qb_s" />
    <title>Vin blanc bio de Bourgogne, le JPH est élaboré à partir de chardonnay issu sur d'une petite parcelle située au pied de l'Abbaye Saint Vivant à Curtil-Vergy.</title>

    <title>LeVinQuiFaitSens</title>
    <%=favicon_link_tag%>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/engagement.html.erb
<div class="content-wrap" >
  <div class="vignette-engagement">
    <h2 class='p-3'>UN IMPACT POSITIF SUR L'ENVIRONNEMENT</h2>
      <div class="description p-3">
        <h4><span id='marge'/>Nous pensons que la simple compensation de l'empreinte carbone n'est pas suffisante, c'est pourquoi nous doublons chaque année cette compensation pour l'empreinte du vin acheté.</h4>
      </div>
    <p class="p-3">Chaque bouteille de vin produit 1,5 Kg d'équivalent CO2. <sup>(1)</sup><br><br> Nous compensons 3 Kg d'équivalent CO2, via la Fondation Good Planet et leur porgramme "Engageons nous en faveur du climat", en fin d'année pour chaque bouteille vendue.</p>
  </div>
</div>

<h6 class="p-3 "><sup>(1)</sup>Le bilan réalisé par l'ADEME donne un résultat de 1,1 Kg d'équivalent CO2 pour une bouteille de vin de 75 cl, avec une amplitude de +/- 50%. Plus d'info sur le site de <a href="http://www.bilans-ges.ademe.fr/documentation/UPLOAD_DOC_FR/index.htm?boissons.htm/">l'ADEME</a>.</h5>

<div class="content-wrap" >
  <div class="vignette-engagement">
    <div>
      <h2>UN PROJET AU SERVICE DES ARTISTES</h2>
    </div>
    <div class="description p-3">
      <h4>La création artistique, moteur de l'innovation.</h4>
    </div>
    <p class="p-3"><span id='marge'/>Afin de perpétuer le projet, nous proposons chaque année à un artiste différent d'interpréter le projet dans son art.<br><br>La première interprétation est faite par Pierre Thilloy, compositeur.
    </p>
  </div>
</div>


<div class="content-wrap" >
  <div class="vignette-engagement">
    <h2>UN PROJET QUI CONTRIBUE A CONSTRUIRE LE FUTUR</h2>
    <div class="description p-3">
      <h4><span id='marge'/>10% du prix de vente (départ propriété) est donné à des porteurs de projets innovants.</h4>
    </div>
    <p class="p-3">Les projets seront choisis par la communauté des clients sur proposition de l'équipe JPH.<br><br>L'équipe JPH, se réunit une fois par an lors des vendanges pour entériner cette sélection.</p>
  </div>
</div>

app/views/pages/histoire.html.erb
<div class="container">
  <div class="row">

    <div class="col-12 col-lg-6 mt-4" style="background-image: url(https://res.cloudinary.com/dbqpc6nk9/image/upload/v1574263640/zdurcpoalk0vscqakjgc.jpg);    background-size: cover;">
    </div>

    <div class="col-12 col-lg-6 p-4">
      <h2 class="pb-3 mt-3" style="color: black; text-align: left;">Une histoire familiale</h2>
      <h4>En 1981, Jean Pierre Halm, créateur de moutarde pour une marque historique dijonnaise et oenologue de formation, acheta la parcelle et y replanta une jeune vigne. Il souhaitait ainsi assouvir sa passion pour le vin et faire de ce lieu un endroit d’expérimentation, pour remettre au goût du jour la recette ancestrale de la moutarde au verjus. Il confie la culture de sa vigne au jeune Patrick Hudelot, viticulteur à Curtil-Vergy.<br><br>Bon vivant, à partir de 1985, il y organise chaque année une rencontre familiale et amicale lors des vendanges.<br><br>Il disparaît à l’âge de 62 ans, en ayant réussit ses expérimentations, mais sans avoir malheureusement pu vinifier lui-même son propre vin.<br><br>Sa famille, notamment sa fille et son gendre avec leurs enfants, perpétuent la tradition familiale....</h4>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<div class="background-image flex-centered" style="background-image: url('https://images.unsplash.com/photo-1504279577054-acfeccf8fc52?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1867&q=80');" >
  <div class="inner-content">
    <h1> <strong>JPH</strong></h1>
    <h1> <strong>Un Vin porteur de valeurs</strong></h1>
  </div>

  <h3 class="pt-3" style="color:white;"> "Vinum Bonum Laetificat Cor Hominis"</h3>
  <div class="pt-5"><%= link_to "Découvrir le vin ", :vin, class: "btn btn-ghost" %></div>
  <i class="fas fa-arrow-down" style="color: rgba(256,256,256,0.65); font-size: xx-large;">   </i>
</div>


  <div class="flex-centered pt-5 pb-5">
    <h1 style="color: black">Notre vision</h1>
    <div class="trait"></div>
    <div class="pl-5 pr-5">
      <h4 class="pl-4 pb-4" style="text-align: center;     align-self: center;">Vous permettre de devenir un acteur de la consommation positive dans un moment de convivialité.<br></h4>
      <h4 class="pb-4"  style="text-align: center;     align-self: center;">Nous sommes attachés à vous apporter un Vin Bio, issu d'un terroir unique, produit en petite quantité et qui s'attache à avoir un impact positif sur notre société.</h4>
    </div>

  </div>


<div class="background-image p-5" style="height: auto;">
  <div class="flex-centered">
    <h1 style="color: black">Nos 4 grands principes</h1>
  <div class="trait"></div>
  </div>

  <div class="cards">

    <div class="big-card">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1423483641154-5411ec9c0ddf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80)">
        Produit
      </div>
      <div class="p-4 text-card">
        <p>Un vin biologique qui permet l'expression du terroir en supprimant l'utilisation de produits chimiques et en produisant une quantité limitée. </p>
      </div>
    </div>

    <div class="big-card">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1416169607655-0c2b3ce2e1cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1334&q=80)">
        Environnement
      </div>
      <div class="p-4 text-card" style="text-align: justify;">
        <p>Une compensation de 200% de l'empreinte carbone du vin produit. </p>
      </div>
    </div>

    <div class="big-card">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1533959679641-8ce0d2962284?ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80)">
        Avenir
      </div>
      <div class="p-4 text-card">
        <p>10% du prix de vente, soit 2 euros par bouteille, est offert à des porteurs de projets innovants à impact positif sur notre société, choisis par notre communauté.  </p>
      </div>
    </div>

    <div class="big-card">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1564053489984-317bbd824340?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1028&q=80)">
        Gouvernance
      </div>
      <div class="p-4 text-card">
        <p>Toutes les décisions concernant la compensation carbone et la contribution aux projets sont prises par la communauté des clients et des vendangeurs.</p>
      </div>
    </div>
  </div>
</div>

<div class="background-image flex-centered pt-5" style="padding-bottom: 28px; background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url(https://images.unsplash.com/photo-1544520533-1b10ed577ab6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80); height: fit-content;">
  <h1>Le JPH en trois chiffres</h1>
  <div class="trait" style="background-color: white;">
  </div>

  <div class="cards" >
    <div class="big-card" style="background-color:rgba(27, 29, 51,0);">
      <div class="card-category reducer-size" style= "box-shadow: none;">
        7,7 <br> ouvrées
      </div>
    </div>


    <div class="big-card" style="background-color:rgba(27, 29, 51,0); ">
      <div class="card-category reducer-size" style= "box-shadow: none;">
        500 <br> bouteilles maximum
      </div>
    </div>


    <div class="big-card" style="background-color:rgba(27, 29, 51,0);">
      <div class="card-category reducer-size" style= "box-shadow: none;">
        30 <br> ans
      </div>
    </div>
  </div>
</div>

app/views/pages/nous.html.erb
<div class="background-image flex-centered" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dbqpc6nk9/image/upload/v1574263665/h9gr6wyoq9fop23fu8w6.jpg);    background-size: cover;">
  <div class="inner-content pl-2 pr-2" style="    margin: auto;">
<div style="background-image: url(../../../app/assets/images/Logo-JPH-sans-fond.png)"> </div>

    <h2><span id='marge'/>Frédérique, Franck ainsi que leurs fils Antoine et Paul, continuent tous les ans à perpétuer l'aventure du JPH. Chaque année une équipe d'une dizaine de vendangeurs bénévoles et surmotivés s'associe à ces moments de convivialité pour récolter les précieuses grappes d'un Vinquifaitsens.</h2>
  </div>
</div>

app/views/pages/terroir.html.erb
<div class="photo-supperieure" style="background-image: url('https://www.grandibottiglie.com/img/cms/Abbaye%20Saint%20Vivant.jpg');">

  </div>
<div class="container">
  <div class="row">

    <div class="col-12 col-lg-3">
        <div class="p-3"><h2  style="color: black; text-align: left;">Un lieu chargé d'histoire</h2></div>
    </div>

    <div class="col-12 col-lg-9 p-3" >
      <div><h4>La parcelle appelée Les Jardins, est située sur  la butte de Vergy à 380 mètres d'altitude, au pied de l’ancienne Abbaye des moines de Saint-Vivant. <br><br>Cette abbaye, fondée aux environs de l'an 900, a abrité des moines bénédictins et cisterciens. Par leur travail, ils ont contribué à définir les fameux "climats de Bourgogne". <br><br>À partir de 1232, ces moines exploiteront, pendant 650 ans, le Clos de la Romanée-Conti et Romanée-Saint-Vivant.</h4>
      </div>
    </div>

  </div>

  <div class="row">
    <div class="col-12 col-lg-6 p-3" style="text-align: justify;">
        <h2 style="color: black; padding-bottom: 4rem; padding-top: 2rem;">Un terroir unique</h2>
         <h4>La parcelle d'une superficie de 7,7 ouvrées soit 33 ares, est exposée plein sud. Cette exposition permet au Chardonnay d'exprimer tout son potentiel dans cette partie de la Bourgogne plus fraîche que la côte.<br><br>Le sol est argilo-calcaire et issu du Jurassique inférieur. Très caillouteux, il permet une bonne infiltration de l'eau. Quand le soleil chauffe, il emmagasine la chaleur pour la restituer à la vigne. Dans le haut de la parcelle, l'enherbement est de rigueur, afin de limiter l'érosion des sols. Cet enherbement naturel est cohérent avec la conversion en bio.<br><br>En 1961, cette terre a reçu l'appellation d'origine contrôlée Hautes-Côtes-de-Nuits. </h4>
    </div>
    <div class="col-12 col-lg-6 p-3">
      <div>
        <div class="vignette" style="background-image: url('https://res.cloudinary.com/dbqpc6nk9/image/upload/v1574268174/engagement-5_euros_hoygf4.jpg')"></div>
        <div class="vignette" style="background-image: url('https://images.unsplash.com/photo-1515779122185-2390ccdf060b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80')"></div>
      </div>
    </div>
  </div>
</div>

app/views/pages/vin.html.erb
<div class="diapo-photo-supperieure" style="height: all;">
  <div class="photo-supperieure flex-centered" style="    place-content: space-around; background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)),url(https://images.unsplash.com/photo-1560089168-4169937e37d5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1502&q=80);">
    <div><%= link_to "Nous contacter", :contact, class: "btn btn-ghost btn-buy" %></div>
  </div>
</div>

<div class="content-vertical" style="background-color: white; align-items: center;">
  <div class="pt-5 pl-3" style="" ><h2  style="color: black;">Une production limitée</h2></div>
  <div class="p-3"><h4>Chaque année, nous ne commercialisons au maximum qu'un nombre limité de bouteilles. La quantité n'est connue qu'à la fin de la vendange.</h4></div>
</div>

<div class="container">


  <div class="row">
    <div class="col-12 col-lg-6 p-3 pt-4">
        <div>
          <div class="vignette" style="background-image: url('https://images.unsplash.com/photo-1472352327492-9765783b74e1?ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80') "></div>
          <div class="vignette" style="background-image: url('https://res.cloudinary.com/dbqpc6nk9/image/upload/v1574267729/IMG_20190928_093739_ht8v1i.jpg')"></div>
        </div>
    </div>

    <div class="col-12 col-lg-6 p-3 pt-5">
        <h2 style="color: black;">Un vin bio</h2>
        <h4><span id='marge'/>La naissance de ce vin est la rencontre de deux hommes, Jean Pierre Halm et Patrick Hudelot, tous deux passionnés par leur terroir et soucieux de préserver l’environnement et le patrimoine.<br><br>Fin des années 90, Patrick se pose des questions sur la viticulture de main et décide d’entreprendre une conversion en bio, peu avant la disparition de Jean Pierre. Après beaucoup d’efforts, il obtient l’agrément en 2003.<br><br>Cela fait plus de 15 ans que la parcelle est cultivée en bio. Aucun produit chimique, du désherbant aux pesticides, n'est utilisé. Dans les Hautes Côtes, la majorité des rangs de vignes sont espacés et taillés en hauteur, ce qui facilite le travail.<br><br> Les vendanges de la parcelle « Les Jardins » sont exclusivement faites à la main et par l’équipe JPH. Il faut une quinzaine de vendangeurs pour cueillir les quelques 10 000 grappes dorées.<br><br>L'élevage dure de 9 à 12 mois dans des tonneaux fabriqués par des tonneliers bourguignons avec du chêne issu de forêts françaises.<br><br>Le cépage Chardonnay exprime son terroir minéral avec des arômes de fruits blancs et d'agrumes. Lors de son élevage, il peut exprimer de légères notes toastées, caractéristiques des grands vins blancs de Bourgogne.
    </div>
  </div>
</div>


    <div>
      <img style="margin: 0 10vw 0 10vw; width: 80vw;" src="https://res.cloudinary.com/dbqpc6nk9/image/upload/v1575053678/spadel-vin-ambiance-6_pxyez2.jpg" alt="">

    </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<p class = "p-3" style= "text-align: center;"><strong>L'ABUS D'ALCOOL EST DANGEREUX POUR LA SANTÉ, À CONSOMMER AVEC MODÉRATION﻿</p></strong>
<div class="footer p-3">
    <%= link_to "Qui sommes-nous ?", :nous%>
    <%= link_to "CGV", :cgv%>
    <%= link_to "Mentions légales", :mentionslegales%>
    <%= link_to "Données personnelles", :donneepersonnelles%>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo-vigne.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav navbar-center mr-auto">
      <li class="nav-item">
        <%= link_to "Home", home_path, class: "nav-link", style:"padding-right: 1.5rem" %>
      </li>
      <li class="nav-item">
        <%= link_to "Histoire", histoire_path, class: "nav-link", style:"padding-right: 1.5rem" %>
      </li>
      <li class="nav-item">
        <%= link_to "Terroir", terroir_path, class: "nav-link", style:"padding-right: 1.5rem"%>
      </li>
      <li class="nav-item">
        <%= link_to "Vin", vin_path, class: "nav-link", style:"padding-right: 1.5rem" %>
      </li>
      <li class="nav-item">
        <%= link_to "Engagements", engagement_path, class: "nav-link", style:"padding-right: 1.5rem" %>
      </li>


    </ul>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  </div>
</div>